### ISSUE TITLE
Website Issue

### ISSUE THREAD

**Issue by easternwawoman** [litecoin-project/lips#1]
There is one page on website that lists vendors accepting litecoin.  I was delighted to see that page.  I next began going to each vendor.  That's when my delight changed to disappointment.  The links were sour in a variety of ways: did not accept LTC any longer, did not publicily display an accept ltc logo, questionable quality of site.   I contacted one vendor who told me that only BTC could be used as they had a problem accepting LTC because of an issue with the payment provider.  I thought Overstock accepted LTC.  It's not listed.  As LTC is different from BTC in that it can/should be used for small, everyday purchases, I'd like more care taken of this particular page.  I had to check myself as I left feeling my perception of LTC changed despite the fact that I know we're still at adopter stage.  Tap a PR person on how that page can be remodeled to get community support for submissions of vendors accepting LTC, help vendors with content on that page as to payment providers, provide incentives to merchants or providers to accept LTC, delete the vendors that are no longer accepting LTC.  Just sharing thoughts that ran through my mind during my visit there.  I'm sure someone else has better or other ideas.  Goal: Don't cause a site visitor to change their perception following a visit to this important and informative page.

**Comment by PWKad** [comment]
This is a repository for Litecoin Improvement Proposals to Litecoin technology I don't think this is for improvement ideas for sites and such.

**Comment by wangxinxi** [comment]
@easternwawoman Although this is not the right place for your suggestion, but can you let me know which webpage are you talking about?

**Comment by easternwawoman** [comment]
Feel free to delete.  I know this is a code repository.  The twitter post seemed vague enough to cause me to think that it was the LTC universe he wanted feedback on and was simply offering this as an easy place to use. As I store my web code at github, my mind connected dots in that way.  Not offended in the slightest.

**Comment by easternwawoman** [comment]
URL: https://litecoin.com/services
